timezone: Asia/ChongQing

permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
pygments: true

kramdown:
  input: GFM

author:                                     #自定义常量
  name: 神经刀
  email: zzcv.sjd@gmail.com
  link: http://2pporg.com
  github: http://github.com/zzvv

title: 神经刀的杂集                             #自定义常量
description: 神经刀的杂集
url: http://2pporg.com
rss_url: /page/atom.xml

avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: 2pporg.com

# disqus 设置
disqus:
  shortname: zzvv-zh
